### ISSUE TITLE
I don't understand addEvent and can't find an example

### ISSUE THREAD

**Issue by bneijt** [faylang/fay-dom#5]
Seeing there is removeEvent which takes an element, I don't understand why addEvent does not take an element. Furthermore, I can't seem to get addEvent to working. The following example code shows an FFI defined inline that works and the DOM import not working:

```
{-# LANGUAGE EmptyDataDecls, OverloadedStrings #-}
module Sudokucalc where

import FFI
import DOM (addEvent, getElementById)

data Event

addWindowEvent :: String -> (Event -> Fay ()) -> Fay ()
addWindowEvent = ffi "window.addEventListener(%1, %2)"

showEvent :: String -> Event -> Fay()
showEvent prefix event = putStrLn (prefix ++ show event)

setup :: Event -> Fay()
setup event = do
  putStrLn "The document has loaded"
  addEvent "click" (putStrLn "Using addEvent")
  addWindowEvent "click" (showEvent "Using addWindowEvent ")

main :: Fay ()
main = do
  addWindowEvent "load" setup
```

Expected behaviour: on clicking anywhere in the window both "Using addEvent" and "Using addWindowEvent" show up in the console.

Current behaviour: only "Using addWindowEvent" shows up.

**Comment by bergmark** [comment]
> Seeing there is removeEvent which takes an element, I don't understand why addEvent does not take an element.

A mistake, probably.

I don't have a working fay installation at the moment so I can't debug this now, but I'd recommend trying the fay-jquery bindings, it's more mature.

**Comment by ajnsit** [comment]
The code is definitely bitrotten. However it should be easy to fix it and make it do what you want. I opened a PR for `addRequest` here - https://github.com/faylang/fay-dom/pull/6/files.

**Comment by bneijt** [comment]
Thank you, that explains it all. Closing the issue.
